apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: 904484189421.dkr.ecr.us-east-1.amazonaws.com/test1:34fb18e9330786c59000b84953aec99e87aad4e8
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST 
          value: "terraform-2024061617415208630000000d.cjce0c82yelw.us-east-1.rds.amazonaws.com"
        - name: DB_NAME
          value: "bqCore"
        - name: DB_PORT
          value: "5432"
        - name: DB_USERNAME
          value: "postgres"
        - name: DB_PASSWORD
          value: "CORE_ADMIN"
        - name: JWT_SECRET
          value: "hello_beeQuant"
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "2"
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-target-group-arn: "arn:aws:elasticloadbalancing:us-east-1:904484189421:targetgroup/test/b83506f3e9ee31f0"
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: myapp



apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-api
  # namespace: 1-example
spec:
  selector:
    matchLabels:
      app: platform-api
  replicas: 1
  template:
    metadata:
      labels:
        app: platform-api
    spec:
      containers:
      - name: platform-api
        image:904484189421.dkr.ecr.us-east-1.amazonaws.com/test1:34fb18e9330786c59000b84953aec99e87aad4e8
        ports:
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "terraform-2024061617415208630000000d.cjce0c82yelw.us-east-1.rds.amazonaws.com"
        - name: DB_PORT
          value: "5432"
        - name: DB_USERNAME
          value: "postgres"
        - name: DB_PASSWORD
          value: "CORE_ADMIN"
        - name: DB_NAME
          value: "bq_Core"
        - name: JWT_SECRET
          value: "hello_beeQuant"
---
apiVersion: v1
kind: Service
metadata:
  name: platform-api
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /healthcheck
  # namespace: 1-example
spec:
  ports:
  - port: 443
    targetPort: 3000
    protocol: TCP
  type: NodePort
  selector:
    app: platform-api