name: CI pipeline
on:
    workflow_dispatch:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: install dependencies
              run: yarn
            - name: unit tests
              run: yarn run tets
            - name: e2e tets
              run: yarn run tets:e2e
            - name: test coverage
              run: yarn run test:cov
