name: Terraform AWS Deployment

on:
  push:
    branches:
      - tf-test

jobs:
  terraform:
    name: Terraform AWS Deployment
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-southeast-2
      AWS_ACCESS_KEY_ID: AKIA2UC263WHSPMKCS44
      AWS_SECRET_ACCESS_KEY: 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

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" >> $GITHUB_ENV
          aws configure set aws_access_key_id AKIA2UC263WHSPMKCS44
          aws configure set aws_secret_access_key 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
          aws configure set region ap-southeast-2
      - name: Debug AWS CLI Configuration
        run: |
          aws configure list

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Terraform Show
        run: terraform show
